import { writeFileSync, mkdirSync, existsSync, readFileSync } from "fs";

const API_URL = "https://api.hyperliquid.xyz/info";
const CDN_URL = "https://app.hyperliquid.xyz/coins";
const OUTPUT_DIR = "svgs";
const ASSETS_FILE = "assets.json";
const GENERATED_FILE = "src/_assets.ts";
const CONCURRENCY = 3;
const REQUEST_DELAY_MS = 3000;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

async function fetchApi<T>(body: object): Promise<T> {
  const res = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  return res.json();
}

async function fetchAssetList(): Promise<string[]> {
  const [spotData, perpData] = await Promise.all([
    fetchApi<{ tokens: { name: string }[] }>({ type: "spotMeta" }),
    fetchApi<{ universe: { name: string }[] }>({ type: "meta" }),
  ]);
  const spot = spotData.tokens.map((t) => t.name);
  const perp = perpData.universe.map((u) => u.name);
  const combined = [...new Set([...spot, ...perp])];
  writeFileSync(ASSETS_FILE, JSON.stringify(combined, null, 2));
  return combined;
}

function guessVariants(asset: string): string[] {
  const candidates = [asset];
  if (asset.startsWith("k")) candidates.push(asset.slice(1));
  return [...new Set(candidates)];
}

async function downloadOne(asset: string): Promise<string | null> {
  for (const variant of guessVariants(asset)) {
    const url = `${CDN_URL}/${variant}.svg`;
    try {
      const res = await fetch(url);
      if (!res.ok) continue;
      const svg = await res.text();
      if (svg.includes("<svg")) return svg;
    } catch {
      continue;
    }
  }
  return null;
}

async function downloadAll(assets: string[]): Promise<Map<string, string>> {
  if (!existsSync(OUTPUT_DIR)) mkdirSync(OUTPUT_DIR);

  const map = new Map<string, string>();
  const queue = [...assets];
  let done = 0;

  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      while (queue.length) {
        const asset = queue.shift()!;
        await sleep(REQUEST_DELAY_MS);
        const svg = await downloadOne(asset);
        if (svg) {
          map.set(asset, svg);
          writeFileSync(`${OUTPUT_DIR}/${sanitize(asset)}.svg`, svg);
        }
        done++;
        process.stdout.write(`\r${done}/${assets.length} (${map.size} ok)`);
      }
    }),
  );

  console.log();
  return map;
}

function escapeSvg(svg: string): string {
  return svg
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");
}

function generateSource(map: Map<string, string>, allAssets: string[]) {
  const available = allAssets.filter((a) => map.has(a));
  const entries = available
    .map((a) => `  ["${a}"]: \`${escapeSvg(map.get(a)!)}\`,`)
    .join("\n");

  const code = `// Auto-generated by scripts/fetch-svgs.ts
export const svgMap: Record<string, string> = {
${entries}
};

export const assets: string[] = ${JSON.stringify(available)};
`;

  writeFileSync(GENERATED_FILE, code);
  console.log(`Generated ${GENERATED_FILE} with ${available.length} SVGs`);
}

async function main() {
  const fromApi = process.argv.includes("--live");
  const allAssets = fromApi ? await fetchAssetList() : (
    JSON.parse(readFileSync(ASSETS_FILE, "utf-8")) as string[]
  );
  console.log(`Found ${allAssets.length} assets`);

  console.log("Downloading SVGs...");
  const map = await downloadAll(allAssets);

  console.log(`Success: ${map.size}/${allAssets.length}`);

  console.log("Generating src/_assets.ts...");
  generateSource(map, allAssets);

  console.log("Done!");
}

main();
